# Marca de Agua en Señales de Audio

Este Jupyter Notebook presenta el código que muestra el desarrollo experimental presentado en el informe "Marca de Agua en Señales de Audio".

Se importan todas las bibliotecas que serán utilizadas.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
from scipy.fft import fft
import scipy.signal as sig
import cv2

In [1]:
pip install opencv-python

Note: you may need to restart the kernel to use updated packages.


### Agregado de la marca de agua

In [ ]:
# Cargamos la señal que queremos meterle la marca de agua
# La ploteamos

In [ ]:
# Calculamos la STFT de la señal, con el checkeo de criterios y todo lo que pusimos de stft como en la Guía 1.
# Ploteamos STFT

In [ ]:
# Aplicamos SVD a la matriz STFT

In [10]:
# Cargamos la imagen que queremos incrustar a la señal, la convertimos en byn, la convertimos en una secuencia binaria y dimensionamos
img = cv2.imread('Pierre-Simon-Laplace.jpg', 2) # lee el archivo de imagen
# cv2.imshow('image', img)
# cv2.waitKey(0)
ret, bw_img = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY) # aplica un umbral para determinar qué es 0 y que es 1. bw_img es la imagen en binario
bw = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY) # tupla: (ret, bw_img) 

cv2.imshow('Binary', bw_img) 
cv2.waitKey(0)
cv2.destroyAllWindows()

In [8]:
print(str(ret))
print(str(type(ret)))

print(str(bw_img))
print(str(type(bw_img)))

print(str(bw))
print(str(type(bw)))

127.0
<class 'float'>
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>
(127.0, array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8))
<class 'tuple'>


In [14]:
sec_binaria = bw_img.flatten() # matriz imagen a array unidimensional
print('Dimension de matriz imagen: '+ str(bw_img.shape))
print('Dimension de secuencia generada: '+ str(sec_binaria.shape))

Dimension de matriz imagen: (1190, 920)
Dimension de secuencia generada: (1094800,)


In [ ]:
# El tema de truncar el array para que las dimensiones den bien lo podemos hacer con algo tipo:
# sec_truncada = sec_binaria[:len('algo')]
# de esa manera aseguramos que según que audio e imagen usemos van a funcionar bien las dimensiones para operar (igual hay que ver como mezclamos marca de agua y audio)

In [ ]:
# Acá tendríamos que ver como la metemos en la matriz STFT...

### Detección de la marca de agua

In [ ]:
# Presentamos todas las cosas que se necesitan para detectar la marca de agua, y hacemos alguna prueba o algo.

### Parámetros para evaluar el resultado

In [ ]:
# Acá calculamos PSNR yu NC para la señal con marca de agua que tenemos hasta el momento.

### Pruebas modificando la señal resultante

In [ ]:
# 'Ataques' mas o menos simples para determinar la robustez de la marca de agua.